export const firebaseImgUrl =
  "https://firebasestorage.googleapis.com/v0/b/total-mobility-solution-6c7cc.firebasestorage.app/o";

export const getStartedGoogleSheetUrl =
  "https://script.google.com/macros/s/AKfycbwT7S3bt42oUicC5pAKciCbn3njpA_zYHOJEafx_17Bc_7a8h6HE8G5yNK-mie-IifY/exec";

export const pageRoutes = {
  blog: "/blog",
  comingSoon: "/coming-soon",
  contactUs: "/contact",
  deviceSecurity: "/device-security",
  faqs: "/#faqs",
  getStarted: "/get-started",
  home: "/",
  homeScroll: "/#home",
  intoTheFuture: "/into-the-future",
  login: "/login",
  noDowntimeFaq: "/#no-downtime-faq",
  ourStory: "/our-story",
  partners: "/partners",
  partnersForm: "/partners/form",
  pricing: "/#pricing",
  privateRoutes: {
    dashboard: "/dashboard",
    invoices: "/dashboard/invoices",
    invoiceForm: "dashboard/invoice-form",
    sparesInventory: "/dashboard/spares-inventory",
    supportTickets: "/dashboard/support-tickets",
  },
  supportRequest: "/support-request",
  whyTms: "/why-tms",
};

export const calendlyLink = "https://calendly.com/totalmobilitysolution/15min";
export const storageKeys = {
  companyInfo: "companyInfo",
};

export const states = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
];
